#!/usr/bin/env python3
"""Scan CFD directory and generate experiment/stimuli.js manifest."""

import json
import re
from datetime import date
from pathlib import Path

CFD_ROOT = Path(__file__).resolve().parent.parent / "materials" / "cfd" / "Images" / "CFD"
OUTPUT = Path(__file__).resolve().parent.parent / "experiment" / "stimuli.js"

WANTED_EXPRESSIONS = {"N", "A", "HC", "HO"}

# Matches filenames like: CFD-BF-001-026-A.jpg, CFD-WM-234-018-HC.jpg, CFD-AF-215-70-N.jpg
FILENAME_PATTERN = re.compile(
    r"^CFD-([A-Z]{1,2})([FM])-(\d{2,3})-(\d{2,3})-([A-Z]{1,2})\.jpg$"
)


def scan():
    models = []

    for model_dir in sorted(CFD_ROOT.iterdir()):
        if not model_dir.is_dir():
            continue

        dirname = model_dir.name  # e.g. "BF-001"
        parts = dirname.split("-")
        if len(parts) != 2:
            continue

        race_gender = parts[0]  # e.g. "BF"
        if len(race_gender) < 2:
            continue

        race = race_gender[:-1]   # "B", "W", "A", "L"
        gender = race_gender[-1]  # "F" or "M"

        expressions = {}
        for img_file in sorted(model_dir.iterdir()):
            m = FILENAME_PATTERN.match(img_file.name)
            if not m:
                continue
            expr = m.group(5)
            if expr in WANTED_EXPRESSIONS:
                rel_path = f"materials/cfd/Images/CFD/{dirname}/{img_file.name}"
                expressions[expr] = rel_path

        if not expressions:
            continue

        models.append(
            {
                "model_id": dirname,
                "race": race,
                "gender": gender,
                "expressions": expressions,
            }
        )

    return models


def write_js(models):
    header = (
        f"// Auto-generated by scripts/generate_manifest.py -- DO NOT EDIT\n"
        f"// Generated: {date.today().isoformat()}\n"
        f"// Source: materials/cfd/Images/CFD/ ({len(models)} models)\n"
    )
    js_array = json.dumps(models, indent=2)
    OUTPUT.write_text(f"{header}const STIMULI = {js_array};\n")
    print(f"Wrote {len(models)} models to {OUTPUT}")

    # Summary by race-gender
    from collections import Counter

    rg_counts = Counter(f"{m['race']}{m['gender']}" for m in models)
    for rg in sorted(rg_counts):
        expr_counts = {}
        for m in models:
            if f"{m['race']}{m['gender']}" == rg:
                for e in m["expressions"]:
                    expr_counts[e] = expr_counts.get(e, 0) + 1
        print(f"  {rg}: {rg_counts[rg]} models — {expr_counts}")


if __name__ == "__main__":
    models = scan()
    write_js(models)
